version: 2.1

executors:
  copy_vault_testing_files:
    docker: 
      - image: circleci/golang:1.14    
    working_directory: /go/src/github.com/dollarshaveclub/pvc

  gobuild_and_test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true       
    working_directory: ~/go/src/github.com/dollarshaveclub/pvc
jobs:
  copy:
    executor: copy_vault_testing_files
    steps:
      - checkout
      - run: mkdir -p /tmp/opt
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json /tmp/opt/secrets.json
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_app_ids.json /tmp/opt/app-id.json
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_policies.json /tmp/opt/policies.json
      - persist_to_workspace:
          root: /tmp/opt
          paths:
            - secrets.json
            - app-id.json
            - policies.json
  test:
    executor: gobuild_and_test
    steps: 
      - attach_workspace:
          at: /tmp/opt
      - run: ls .
      - run: ls /tmp/opt
      - run: go version
      - run: sudo rm -rf /usr/local/go
      - checkout
      - run: sudo apt-get update
      - run: wget https://golang.org/dl/go1.14.linux-amd64.tar.gz
      - run: sudo tar -xvf go1.14.linux-amd64.tar.gz -C /usr/local 
      - run: export GOBIN="${HOME}/go/bin"
      - run: sudo mkdir -p "${HOME}/go"
      - run: sudo mkdir -p "${HOME}/go/bin"
      - run: export PATH=${PATH}:${GOROOT}/bin:${GOBIN}
      - run: go version
      - run: go build
      - run:
          name: Start Vault
          command: docker run --name vault -d -p 8200:8200 -e "VAULT_API_ADDR=http://0.0.0.0:8200" -v "/tmp/opt/secrets.json:/opt/secrets.json" -v "/tmp/opt/policies:/opt/policies.json" quay.io/dollarshaveclub/vault-dev:master
      - run: ls .    
      - run: export VAULT_ADDR="http://localhost:8200" && export VAULT_TEST_TOKEN=root && export VAULT_DEV_ALREADY_RUNNING=1 && go test -v -race -cover
workflows:
  version: 2

  btd:
    jobs:
      - copy
      - test:
          requires:
            - copy
          