version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - checkout
      - run: go build 
  test:
    docker: 
      - image: docker:stable-git
      - image: circleci/golang:1.14
        environment:
        - VAULT_ADDR: "http://localhost:8200"
        - VAULT_TOKEN: root
        - VAULT_TEST_APPID: testing
        - VAULT_TEST_USERID: asdf
        - VAULT_TEST_TOKEN: root
        - VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - checkout:
      - run: 
          name: Start Vault Dev Server
          command: docker run --name vault -d -p 8200:8200 -e "VAULT_USE_APP_ID=1" -v "${PWD}/pvc/testing/vault_app_ids.json:/opt/app-id.json" -v "${PWD}/pvc/testing/vault_secrets.json:/opt/secrets.json" -v "${PWD}/pvc/testing/vault_policies.json:/opt/policies.json" quay.io/dollarshaveclub/vault-dev:master
      - run: 
          name: Compile PVC Binary
          command: go install github.com/dollarshaveclub/pvc
      - run:
          name: Running tests
          command: go test -v -race -cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
